language: r
dist: trusty
sudo: true
cache: packages
r: 3.5.1
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-tests --no-examples"
before_install:
- sudo apt-get update
- curl -OL $URL
- mv jabba.tar.gz.gpg?dl=0 jabba.tar.gz.gpg
- echo $JAB | gpg --passphrase-fd 0 jabba.tar.gz.gpg
- mkdir $HOME/my.cplex && tar -xvzf jabba.tar.gz --directory $HOME/my.cplex/
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
r_packages:
- devtools
- testthat
- covr
bioc_packages:
- GenomicRanges
- VariantAnnotation
- DNAcopy
r_github_packages:
- mskilab/gUtils
- mskilab/gTrack
- mskilab/gGnome
- mskilab/bamUtils
- mskilab/Ppurple
script:
- travis_wait 90 ./travis-tool.sh run_tests
after_failure:
- "./travis-tool.sh dump_logs"
env:
  global:
  - secure: W5ZnqwUcd23wTcVqAYXOz9wtn12vK5R5C1nj1YYIqZJqqAZgu7jgL5j98TSf3uW6AR8enPBQDjGzNAK63gin+fpLhq560G0Cb5akSPexPkrikX7hCsm0APzaNsDXtXGiUPSC7ZuTU7t59oE+Tk2tJEGNPMCRjypzt10a6J2r6HcpyGVv4tvWrZizh3H+7F/M2C0qoaa3crHNBv7fzEinuTOXg6cHz6oJjFBVOY+zOgzSfG62NWxW1NVRfdeF1WAWeWdRei1++9Eh/CRI2ag4/e91oBtSudme0NaVzUkbMmsrzlwmYkUFTllOQn/gc9qLgaEJlQsW0VHv81YzzZ6dC3j5PQfmqWSRzl6qi/Q5CBg/qkq8lKbe2pZqQvLAnnPiY4MP7shqd1w++wNRKj+tjssTxOcX2S7kUh7CyszhX8r7jA9jmLYi0tqEtP6NHx5lkOGoztT9x73e2cpz92i7NvxzsVBM23QvuD8auZCtmWXNpa5/RQJtixFYERtBpNSHVisq/Jg5VpALM8oOPNa0o77I5MTbthZxbZfkxVxldNkShCnwkou6gFmPz8eBOu0uYoLiS2pZPnec75Cx0LByRNCr6oyE2fLad8Q4ADU8rm4f7KelwzlPmw+lGW2+X8xFLZliUIIlJ/V6+Ss6DFxWmEbAIsUE35cz9ukdyax+uAc=
  - CPLEX_DIR=$HOME/my.cplex/
  - CPLEX_INCLUDE_PATH=$HOME/my.cplex/include
  - CPLEX_LIB_PATH=$HOME/my.cplex/lib
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --no-examples"
  - _R_CHECK_TESTS_NLINES_=0
  - secure: QiBIHIKlCnkacBth0I7uSzWh22GN3ZibleS3YLQ63elHj2jimgKnU83yPVTIYUWG8mA4WpQ27k1cab/0TfG7Vsv97IwlDDZccPwM1wRSu5hnwBK1ozKd4zQG046QO93gBYOmJRhiD2xGv57uB+j8F7k0RCWNibZDQ/XUcSs6x/gBezGRq9756wCy1X270Eh17rcPivfb1Tl3y+ZShnFRwrauuh+AWipnlgJPqQku484ZbiY7XxDaujpep3M/7lpj2MhfthzqQzNVFQ8gQ39QokD8B+YTS0EbtJK6SlQRuT7ug5G4kKLDcaFoLVaF5KYHyQHYfP/fP70v689P/1kyF1lk40kk1zK93Skgk4n6rGMfi1+IkiKeFNAGKSD0JCUrohKd5KrGTuer85w/2nkNAO65vrH/WMNA71oXNaz0aFF37+hueY/4n4TzwBCsly2DBd23VQGTmX8eJOlgUoSfFi51Zdc6k/0fc9koaGGfqbdr0nAQownSR2AUL0DgK8D5U3xS5Nv0yRftGynui6eOUYUwNGwWcJ6+wgZErcpOpwlrqvCFpZi1DgBpIB60D7BgKXZGChVPhuntDLkxkxf9tOrnGO5y3sVjqyCyVLSjimYRRbBGzFXsIlT78zwFIPaKgVzErS4l33fISUQ5Gv93iKAfnj1nym1uWZHTB/xS4fI=
