## See https://github.com/metacran/r-builder for details.

language: r
sudo: required 

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - ./install_bioc.sh 

r_github_packages:
  - jimhester/covr 

install:
  - ./pkg-build.sh install_deps
  - ./travis-tool.sh install_bioc GenomicRanges
  - ./travis-tool.sh install_bioc DNACopy
  - ./travis-tool.sh install_bioc rtracklayer
  - ./travis-tool.sh install_github mskilab/gUtils
  - ./travis-tool.sh install_github mskilab/gTrack

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
